# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 19:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('project_key', models.IntegerField(db_index=True, default=0, verbose_name='Key')),
                ('project_name', models.CharField(max_length=20, verbose_name='Name')),
                ('project_version', models.FloatField(max_length=10, verbose_name='Version')),
                ('project_class', models.CharField(max_length=10, verbose_name='Class')),
                ('project_contact_primary', models.CharField(max_length=20, verbose_name='Primary Contact')),
                ('project_contact_secondary', models.CharField(blank=True, default='None', max_length=20, null=True, verbose_name='Secondary Contact')),
                ('compute_jan', models.CharField(choices=[('128', 128), ('512', 512), ('1024', 1024)], default=('128', 128), max_length=4, verbose_name='January')),
                ('compute_feb', models.CharField(choices=[('128', 128), ('512', 512), ('1024', 1024)], default=('128', 128), max_length=4, verbose_name='February')),
                ('compute_mar', models.CharField(choices=[('128', 128), ('512', 512), ('1024', 1024)], default=('128', 128), max_length=4, verbose_name='March')),
                ('compute_apr', models.CharField(choices=[('128', 128), ('512', 512), ('1024', 1024)], default=('128', 128), max_length=4, verbose_name='April')),
                ('compute_may', models.CharField(choices=[('128', 128), ('512', 512), ('1024', 1024)], default=('128', 128), max_length=4, verbose_name='May')),
                ('compute_jun', models.CharField(choices=[('128', 128), ('512', 512), ('1024', 1024)], default=('128', 128), max_length=4, verbose_name='June')),
                ('compute_jul', models.CharField(choices=[('128', 128), ('512', 512), ('1024', 1024)], default=('128', 128), max_length=4, verbose_name='July')),
                ('compute_aug', models.CharField(choices=[('128', 128), ('512', 512), ('1024', 1024)], default=('128', 128), max_length=4, verbose_name='August')),
                ('compute_sep', models.CharField(choices=[('128', 128), ('512', 512), ('1024', 1024)], default=('128', 128), max_length=4, verbose_name='September')),
                ('compute_oct', models.CharField(choices=[('128', 128), ('512', 512), ('1024', 1024)], default=('128', 128), max_length=4, verbose_name='October')),
                ('compute_nov', models.CharField(choices=[('128', 128), ('512', 512), ('1024', 1024)], default=('128', 128), max_length=4, verbose_name='November')),
                ('compute_dec', models.CharField(choices=[('128', 128), ('512', 512), ('1024', 1024)], default=('128', 128), max_length=4, verbose_name='December')),
                ('storage_jan', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='January')),
                ('storage_feb', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='February')),
                ('storage_mar', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='March')),
                ('storage_apr', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='April')),
                ('storage_may', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='May')),
                ('storage_jun', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='June')),
                ('storage_jul', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='July')),
                ('storage_aug', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='August')),
                ('storage_sep', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='September')),
                ('storage_oct', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='October')),
                ('storage_nov', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='November')),
                ('storage_dec', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='December')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project_function', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.Function')),
            ],
            options={
                'verbose_name': 'historical project',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_key', models.IntegerField(default=0, unique=True, verbose_name='Key')),
                ('project_name', models.CharField(max_length=20, verbose_name='Name')),
                ('project_version', models.FloatField(max_length=10, verbose_name='Version')),
                ('project_class', models.CharField(max_length=10, verbose_name='Class')),
                ('project_contact_primary', models.CharField(max_length=20, verbose_name='Primary Contact')),
                ('project_contact_secondary', models.CharField(blank=True, default='None', max_length=20, null=True, verbose_name='Secondary Contact')),
                ('compute_jan', models.CharField(choices=[('128', 128), ('512', 512), ('1024', 1024)], default=('128', 128), max_length=4, verbose_name='January')),
                ('compute_feb', models.CharField(choices=[('128', 128), ('512', 512), ('1024', 1024)], default=('128', 128), max_length=4, verbose_name='February')),
                ('compute_mar', models.CharField(choices=[('128', 128), ('512', 512), ('1024', 1024)], default=('128', 128), max_length=4, verbose_name='March')),
                ('compute_apr', models.CharField(choices=[('128', 128), ('512', 512), ('1024', 1024)], default=('128', 128), max_length=4, verbose_name='April')),
                ('compute_may', models.CharField(choices=[('128', 128), ('512', 512), ('1024', 1024)], default=('128', 128), max_length=4, verbose_name='May')),
                ('compute_jun', models.CharField(choices=[('128', 128), ('512', 512), ('1024', 1024)], default=('128', 128), max_length=4, verbose_name='June')),
                ('compute_jul', models.CharField(choices=[('128', 128), ('512', 512), ('1024', 1024)], default=('128', 128), max_length=4, verbose_name='July')),
                ('compute_aug', models.CharField(choices=[('128', 128), ('512', 512), ('1024', 1024)], default=('128', 128), max_length=4, verbose_name='August')),
                ('compute_sep', models.CharField(choices=[('128', 128), ('512', 512), ('1024', 1024)], default=('128', 128), max_length=4, verbose_name='September')),
                ('compute_oct', models.CharField(choices=[('128', 128), ('512', 512), ('1024', 1024)], default=('128', 128), max_length=4, verbose_name='October')),
                ('compute_nov', models.CharField(choices=[('128', 128), ('512', 512), ('1024', 1024)], default=('128', 128), max_length=4, verbose_name='November')),
                ('compute_dec', models.CharField(choices=[('128', 128), ('512', 512), ('1024', 1024)], default=('128', 128), max_length=4, verbose_name='December')),
                ('storage_jan', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='January')),
                ('storage_feb', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='February')),
                ('storage_mar', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='March')),
                ('storage_apr', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='April')),
                ('storage_may', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='May')),
                ('storage_jun', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='June')),
                ('storage_jul', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='July')),
                ('storage_aug', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='August')),
                ('storage_sep', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='September')),
                ('storage_oct', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='October')),
                ('storage_nov', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='November')),
                ('storage_dec', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='December')),
                ('project_function', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='project.Function')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_site',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='project.Site'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='project_site',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.Site'),
        ),
    ]
