# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20170727_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='compute_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.ComputeProfile'),
        ),
    ]
