# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 18:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0009_auto_20170727_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalComputeProfile',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('slots_or_hosts', models.CharField(choices=[('Slots', 'Slots'), ('Hosts', 'Hosts'), ('Both', 'Both')], max_length=5)),
                ('compute_size', models.CharField(choices=[('128', 128), ('512', 512), ('1028', 1028)], max_length=4)),
                ('compute_jan', models.CharField(max_length=4, verbose_name='January-17')),
                ('compute_feb', models.CharField(max_length=4, verbose_name='February-17')),
                ('compute_mar', models.CharField(max_length=4, verbose_name='March-17')),
                ('compute_apr', models.CharField(max_length=4, verbose_name='April-17')),
                ('compute_may', models.CharField(max_length=4, verbose_name='May-17')),
                ('compute_jun', models.CharField(max_length=4, verbose_name='June-17')),
                ('compute_jul', models.CharField(max_length=4, verbose_name='July-17')),
                ('compute_aug', models.CharField(max_length=4, verbose_name='August-17')),
                ('compute_sep', models.CharField(max_length=4, verbose_name='September-17')),
                ('compute_oct', models.CharField(max_length=4, verbose_name='October-17')),
                ('compute_nov', models.CharField(max_length=4, verbose_name='November-17')),
                ('compute_dec', models.CharField(max_length=4, verbose_name='December-17')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical compute profile',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalStorageProfile',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('storage_tier', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], max_length=2)),
                ('storage_size', models.CharField(choices=[('GB', 'GB'), ('TB', 'TB')], max_length=2)),
                ('storage_jan', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='January')),
                ('storage_feb', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='February')),
                ('storage_mar', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='March')),
                ('storage_apr', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='April')),
                ('storage_may', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='May')),
                ('storage_jun', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='June')),
                ('storage_jul', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='July')),
                ('storage_aug', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='August')),
                ('storage_sep', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='September')),
                ('storage_oct', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='October')),
                ('storage_nov', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='November')),
                ('storage_dec', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='December')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical storage profile',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='StorageProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_tier', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], max_length=2)),
                ('storage_size', models.CharField(choices=[('GB', 'GB'), ('TB', 'TB')], max_length=2)),
                ('storage_jan', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='January')),
                ('storage_feb', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='February')),
                ('storage_mar', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='March')),
                ('storage_apr', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='April')),
                ('storage_may', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='May')),
                ('storage_jun', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='June')),
                ('storage_jul', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='July')),
                ('storage_aug', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='August')),
                ('storage_sep', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='September')),
                ('storage_oct', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='October')),
                ('storage_nov', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='November')),
                ('storage_dec', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=('T1', 'T1'), max_length=2, verbose_name='December')),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='storage_apr',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='storage_aug',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='storage_dec',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='storage_feb',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='storage_jan',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='storage_jul',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='storage_jun',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='storage_mar',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='storage_may',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='storage_nov',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='storage_oct',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='storage_sep',
        ),
        migrations.RemoveField(
            model_name='project',
            name='storage_apr',
        ),
        migrations.RemoveField(
            model_name='project',
            name='storage_aug',
        ),
        migrations.RemoveField(
            model_name='project',
            name='storage_dec',
        ),
        migrations.RemoveField(
            model_name='project',
            name='storage_feb',
        ),
        migrations.RemoveField(
            model_name='project',
            name='storage_jan',
        ),
        migrations.RemoveField(
            model_name='project',
            name='storage_jul',
        ),
        migrations.RemoveField(
            model_name='project',
            name='storage_jun',
        ),
        migrations.RemoveField(
            model_name='project',
            name='storage_mar',
        ),
        migrations.RemoveField(
            model_name='project',
            name='storage_may',
        ),
        migrations.RemoveField(
            model_name='project',
            name='storage_nov',
        ),
        migrations.RemoveField(
            model_name='project',
            name='storage_oct',
        ),
        migrations.RemoveField(
            model_name='project',
            name='storage_sep',
        ),
        migrations.AlterField(
            model_name='computeprofile',
            name='compute_size',
            field=models.CharField(choices=[('128', 128), ('512', 512), ('1028', 1028)], max_length=4),
        ),
        migrations.AlterField(
            model_name='computeprofile',
            name='slots_or_hosts',
            field=models.CharField(choices=[('Slots', 'Slots'), ('Hosts', 'Hosts'), ('Both', 'Both')], max_length=5),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='storage_profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.StorageProfile'),
        ),
        migrations.AddField(
            model_name='project',
            name='storage_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.StorageProfile'),
        ),
    ]
