# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20170731_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_apr',
            field=models.CharField(max_length=2, verbose_name='April'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_aug',
            field=models.CharField(max_length=2, verbose_name='August'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_dec',
            field=models.CharField(max_length=2, verbose_name='December'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_feb',
            field=models.CharField(max_length=2, verbose_name='February'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_jan',
            field=models.CharField(max_length=2, verbose_name='January'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_jul',
            field=models.CharField(max_length=2, verbose_name='July'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_jun',
            field=models.CharField(max_length=2, verbose_name='June'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_mar',
            field=models.CharField(max_length=2, verbose_name='March'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_may',
            field=models.CharField(max_length=2, verbose_name='May'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_nov',
            field=models.CharField(max_length=2, verbose_name='November'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_oct',
            field=models.CharField(max_length=2, verbose_name='October'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_sep',
            field=models.CharField(max_length=2, verbose_name='September'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_tier',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_apr',
            field=models.CharField(max_length=2, verbose_name='April'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_aug',
            field=models.CharField(max_length=2, verbose_name='August'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_dec',
            field=models.CharField(max_length=2, verbose_name='December'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_feb',
            field=models.CharField(max_length=2, verbose_name='February'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_jan',
            field=models.CharField(max_length=2, verbose_name='January'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_jul',
            field=models.CharField(max_length=2, verbose_name='July'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_jun',
            field=models.CharField(max_length=2, verbose_name='June'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_mar',
            field=models.CharField(max_length=2, verbose_name='March'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_may',
            field=models.CharField(max_length=2, verbose_name='May'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_nov',
            field=models.CharField(max_length=2, verbose_name='November'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_oct',
            field=models.CharField(max_length=2, verbose_name='October'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_sep',
            field=models.CharField(max_length=2, verbose_name='September'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_tier',
            field=models.CharField(max_length=2),
        ),
    ]
