# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20170802_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computeprofile',
            name='compute_size',
            field=models.CharField(choices=[('128 GB', 128), ('512 GB', 512), ('1028 GB', 1028)], max_length=4),
        ),
        migrations.AlterField(
            model_name='historicalcomputeprofile',
            name='compute_size',
            field=models.CharField(choices=[('128 GB', 128), ('512 GB', 512), ('1028 GB', 1028)], max_length=4),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_apr',
            field=models.CharField(max_length=3, verbose_name='April-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_aug',
            field=models.CharField(max_length=3, verbose_name='August-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_dec',
            field=models.CharField(max_length=3, verbose_name='December-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_feb',
            field=models.CharField(max_length=3, verbose_name='February-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_jan',
            field=models.CharField(max_length=3, verbose_name='January-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_jul',
            field=models.CharField(max_length=3, verbose_name='July-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_jun',
            field=models.CharField(max_length=3, verbose_name='June-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_mar',
            field=models.CharField(max_length=3, verbose_name='March-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_may',
            field=models.CharField(max_length=3, verbose_name='May-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_nov',
            field=models.CharField(max_length=3, verbose_name='November-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_oct',
            field=models.CharField(max_length=3, verbose_name='October-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_sep',
            field=models.CharField(max_length=3, verbose_name='September-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_tier',
            field=models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], max_length=2),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_apr',
            field=models.CharField(max_length=3, verbose_name='April-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_aug',
            field=models.CharField(max_length=3, verbose_name='August-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_dec',
            field=models.CharField(max_length=3, verbose_name='December-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_feb',
            field=models.CharField(max_length=3, verbose_name='February-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_jan',
            field=models.CharField(max_length=3, verbose_name='January-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_jul',
            field=models.CharField(max_length=3, verbose_name='July-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_jun',
            field=models.CharField(max_length=3, verbose_name='June-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_mar',
            field=models.CharField(max_length=3, verbose_name='March-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_may',
            field=models.CharField(max_length=3, verbose_name='May-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_nov',
            field=models.CharField(max_length=3, verbose_name='November-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_oct',
            field=models.CharField(max_length=3, verbose_name='October-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_sep',
            field=models.CharField(max_length=3, verbose_name='September-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_tier',
            field=models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], max_length=2),
        ),
    ]
