# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20170802_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computeprofile',
            name='compute_size',
            field=models.CharField(choices=[('128 GB', '128 GB'), ('512 GB', '512 GB'), ('1028 GB', '1028 GB')], max_length=4),
        ),
        migrations.AlterField(
            model_name='historicalcomputeprofile',
            name='compute_size',
            field=models.CharField(choices=[('128 GB', '128 GB'), ('512 GB', '512 GB'), ('1028 GB', '1028 GB')], max_length=4),
        ),
    ]
