# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20170802_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computeprofile',
            name='compute_jan',
            field=models.CharField(default=0, max_length=3, verbose_name='January-17'),
        ),
        migrations.AlterField(
            model_name='historicalcomputeprofile',
            name='compute_jan',
            field=models.CharField(default=0, max_length=3, verbose_name='January-17'),
        ),
    ]
