# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_auto_20170802_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='project_class',
            field=models.CharField(max_length=11, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_class',
            field=models.CharField(max_length=11, verbose_name='Class'),
        ),
    ]
