# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_auto_20170803_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_function',
            field=models.ForeignKey(blank=True, max_length=20, on_delete=django.db.models.deletion.CASCADE, to='project.Function'),
        ),
    ]
