# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_auto_20170803_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='function',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='site',
            name='site',
            field=models.CharField(max_length=20),
        ),
    ]
