# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_auto_20170803_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computeprofile',
            name='compute_size',
            field=models.CharField(choices=[('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB'), ('1024 GB', '1024 GB'), ('2048 GB', '2048 GB')], max_length=7),
        ),
        migrations.AlterField(
            model_name='historicalcomputeprofile',
            name='compute_size',
            field=models.CharField(choices=[('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB'), ('1024 GB', '1024 GB'), ('2048 GB', '2048 GB')], max_length=7),
        ),
    ]
