# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_auto_20170803_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputeSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compute_size', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='SlotsOrHosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots_or_hosts', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='computeprofile',
            name='compute_apr',
            field=models.CharField(max_length=4, verbose_name='April-17'),
        ),
        migrations.AlterField(
            model_name='computeprofile',
            name='compute_aug',
            field=models.CharField(max_length=4, verbose_name='August-17'),
        ),
        migrations.AlterField(
            model_name='computeprofile',
            name='compute_dec',
            field=models.CharField(max_length=4, verbose_name='December-17'),
        ),
        migrations.AlterField(
            model_name='computeprofile',
            name='compute_feb',
            field=models.CharField(max_length=4, verbose_name='February-17'),
        ),
        migrations.AlterField(
            model_name='computeprofile',
            name='compute_jan',
            field=models.CharField(max_length=4, verbose_name='January-17'),
        ),
        migrations.AlterField(
            model_name='computeprofile',
            name='compute_jul',
            field=models.CharField(max_length=4, verbose_name='July-17'),
        ),
        migrations.AlterField(
            model_name='computeprofile',
            name='compute_jun',
            field=models.CharField(max_length=4, verbose_name='June-17'),
        ),
        migrations.AlterField(
            model_name='computeprofile',
            name='compute_mar',
            field=models.CharField(max_length=4, verbose_name='March-17'),
        ),
        migrations.AlterField(
            model_name='computeprofile',
            name='compute_may',
            field=models.CharField(max_length=4, verbose_name='May-17'),
        ),
        migrations.AlterField(
            model_name='computeprofile',
            name='compute_nov',
            field=models.CharField(max_length=4, verbose_name='November-17'),
        ),
        migrations.AlterField(
            model_name='computeprofile',
            name='compute_oct',
            field=models.CharField(max_length=4, verbose_name='October-17'),
        ),
        migrations.AlterField(
            model_name='computeprofile',
            name='compute_sep',
            field=models.CharField(max_length=4, verbose_name='September-17'),
        ),
        migrations.AlterField(
            model_name='computeprofile',
            name='compute_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.ComputeSize'),
        ),
        migrations.AlterField(
            model_name='computeprofile',
            name='slots_or_hosts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.SlotsOrHosts'),
        ),
        migrations.AlterField(
            model_name='historicalcomputeprofile',
            name='compute_apr',
            field=models.CharField(max_length=4, verbose_name='April-17'),
        ),
        migrations.AlterField(
            model_name='historicalcomputeprofile',
            name='compute_aug',
            field=models.CharField(max_length=4, verbose_name='August-17'),
        ),
        migrations.AlterField(
            model_name='historicalcomputeprofile',
            name='compute_dec',
            field=models.CharField(max_length=4, verbose_name='December-17'),
        ),
        migrations.AlterField(
            model_name='historicalcomputeprofile',
            name='compute_feb',
            field=models.CharField(max_length=4, verbose_name='February-17'),
        ),
        migrations.AlterField(
            model_name='historicalcomputeprofile',
            name='compute_jan',
            field=models.CharField(max_length=4, verbose_name='January-17'),
        ),
        migrations.AlterField(
            model_name='historicalcomputeprofile',
            name='compute_jul',
            field=models.CharField(max_length=4, verbose_name='July-17'),
        ),
        migrations.AlterField(
            model_name='historicalcomputeprofile',
            name='compute_jun',
            field=models.CharField(max_length=4, verbose_name='June-17'),
        ),
        migrations.AlterField(
            model_name='historicalcomputeprofile',
            name='compute_mar',
            field=models.CharField(max_length=4, verbose_name='March-17'),
        ),
        migrations.AlterField(
            model_name='historicalcomputeprofile',
            name='compute_may',
            field=models.CharField(max_length=4, verbose_name='May-17'),
        ),
        migrations.AlterField(
            model_name='historicalcomputeprofile',
            name='compute_nov',
            field=models.CharField(max_length=4, verbose_name='November-17'),
        ),
        migrations.AlterField(
            model_name='historicalcomputeprofile',
            name='compute_oct',
            field=models.CharField(max_length=4, verbose_name='October-17'),
        ),
        migrations.AlterField(
            model_name='historicalcomputeprofile',
            name='compute_sep',
            field=models.CharField(max_length=4, verbose_name='September-17'),
        ),
        migrations.AlterField(
            model_name='historicalcomputeprofile',
            name='compute_size',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.ComputeSize'),
        ),
        migrations.AlterField(
            model_name='historicalcomputeprofile',
            name='slots_or_hosts',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.SlotsOrHosts'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_apr',
            field=models.CharField(max_length=4, verbose_name='April-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_aug',
            field=models.CharField(max_length=4, verbose_name='August-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_dec',
            field=models.CharField(max_length=4, verbose_name='December-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_feb',
            field=models.CharField(max_length=4, verbose_name='February-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_jan',
            field=models.CharField(max_length=4, verbose_name='January-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_jul',
            field=models.CharField(max_length=4, verbose_name='July-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_jun',
            field=models.CharField(max_length=4, verbose_name='June-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_mar',
            field=models.CharField(max_length=4, verbose_name='March-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_may',
            field=models.CharField(max_length=4, verbose_name='May-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_nov',
            field=models.CharField(max_length=4, verbose_name='November-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_oct',
            field=models.CharField(max_length=4, verbose_name='October-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_sep',
            field=models.CharField(max_length=4, verbose_name='September-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_apr',
            field=models.CharField(max_length=4, verbose_name='April-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_aug',
            field=models.CharField(max_length=4, verbose_name='August-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_dec',
            field=models.CharField(max_length=4, verbose_name='December-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_feb',
            field=models.CharField(max_length=4, verbose_name='February-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_jan',
            field=models.CharField(max_length=4, verbose_name='January-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_jul',
            field=models.CharField(max_length=4, verbose_name='July-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_jun',
            field=models.CharField(max_length=4, verbose_name='June-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_mar',
            field=models.CharField(max_length=4, verbose_name='March-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_may',
            field=models.CharField(max_length=4, verbose_name='May-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_nov',
            field=models.CharField(max_length=4, verbose_name='November-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_oct',
            field=models.CharField(max_length=4, verbose_name='October-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_sep',
            field=models.CharField(max_length=4, verbose_name='September-17'),
        ),
    ]
