# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_auto_20170803_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_size', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StorageTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_tier', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_size',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.StorageSize'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_tier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.StorageTier'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.StorageSize'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.StorageTier'),
        ),
    ]
