# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_auto_20170803_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='computeprofile',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Cluster'),
        ),
        migrations.AddField(
            model_name='historicalcomputeprofile',
            name='cluster',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.Cluster'),
        ),
        migrations.AddField(
            model_name='historicalstorageprofile',
            name='cluster',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.Cluster'),
        ),
        migrations.AddField(
            model_name='storageprofile',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Cluster'),
        ),
    ]
