# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_auto_20170803_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Island',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('island', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalstorageprofile',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='storageprofile',
            name='cluster',
        ),
        migrations.AddField(
            model_name='historicalstorageprofile',
            name='island',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.Island'),
        ),
        migrations.AddField(
            model_name='storageprofile',
            name='island',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Island'),
        ),
    ]
