# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_auto_20170807_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='function',
            field=models.CharField(choices=[('PD', 'PD'), ('DFT', 'DFT'), ('PTE', 'PTE')], max_length=20),
        ),
    ]
