# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_auto_20170807_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site',
            field=models.CharField(max_length=20),
        ),
    ]
