# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_auto_20170809_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='project_created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
