# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0035_auto_20170810_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computeprofile',
            name='compute_apr',
            field=models.CharField(max_length=10, verbose_name='April-17'),
        ),
        migrations.AlterField(
            model_name='computeprofile',
            name='compute_aug',
            field=models.CharField(max_length=10, verbose_name='August-17'),
        ),
        migrations.AlterField(
            model_name='computeprofile',
            name='compute_dec',
            field=models.CharField(max_length=10, verbose_name='December-17'),
        ),
        migrations.AlterField(
            model_name='computeprofile',
            name='compute_feb',
            field=models.CharField(max_length=10, verbose_name='February-17'),
        ),
        migrations.AlterField(
            model_name='computeprofile',
            name='compute_jan',
            field=models.CharField(max_length=10, verbose_name='January-17'),
        ),
        migrations.AlterField(
            model_name='computeprofile',
            name='compute_jul',
            field=models.CharField(max_length=10, verbose_name='July-17'),
        ),
        migrations.AlterField(
            model_name='computeprofile',
            name='compute_jun',
            field=models.CharField(max_length=10, verbose_name='June-17'),
        ),
        migrations.AlterField(
            model_name='computeprofile',
            name='compute_mar',
            field=models.CharField(max_length=10, verbose_name='March-17'),
        ),
        migrations.AlterField(
            model_name='computeprofile',
            name='compute_may',
            field=models.CharField(max_length=10, verbose_name='May-17'),
        ),
        migrations.AlterField(
            model_name='computeprofile',
            name='compute_nov',
            field=models.CharField(max_length=10, verbose_name='November-17'),
        ),
        migrations.AlterField(
            model_name='computeprofile',
            name='compute_oct',
            field=models.CharField(max_length=10, verbose_name='October-17'),
        ),
        migrations.AlterField(
            model_name='computeprofile',
            name='compute_sep',
            field=models.CharField(max_length=10, verbose_name='September-17'),
        ),
        migrations.AlterField(
            model_name='computesize',
            name='compute_size',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalcomputeprofile',
            name='compute_apr',
            field=models.CharField(max_length=10, verbose_name='April-17'),
        ),
        migrations.AlterField(
            model_name='historicalcomputeprofile',
            name='compute_aug',
            field=models.CharField(max_length=10, verbose_name='August-17'),
        ),
        migrations.AlterField(
            model_name='historicalcomputeprofile',
            name='compute_dec',
            field=models.CharField(max_length=10, verbose_name='December-17'),
        ),
        migrations.AlterField(
            model_name='historicalcomputeprofile',
            name='compute_feb',
            field=models.CharField(max_length=10, verbose_name='February-17'),
        ),
        migrations.AlterField(
            model_name='historicalcomputeprofile',
            name='compute_jan',
            field=models.CharField(max_length=10, verbose_name='January-17'),
        ),
        migrations.AlterField(
            model_name='historicalcomputeprofile',
            name='compute_jul',
            field=models.CharField(max_length=10, verbose_name='July-17'),
        ),
        migrations.AlterField(
            model_name='historicalcomputeprofile',
            name='compute_jun',
            field=models.CharField(max_length=10, verbose_name='June-17'),
        ),
        migrations.AlterField(
            model_name='historicalcomputeprofile',
            name='compute_mar',
            field=models.CharField(max_length=10, verbose_name='March-17'),
        ),
        migrations.AlterField(
            model_name='historicalcomputeprofile',
            name='compute_may',
            field=models.CharField(max_length=10, verbose_name='May-17'),
        ),
        migrations.AlterField(
            model_name='historicalcomputeprofile',
            name='compute_nov',
            field=models.CharField(max_length=10, verbose_name='November-17'),
        ),
        migrations.AlterField(
            model_name='historicalcomputeprofile',
            name='compute_oct',
            field=models.CharField(max_length=10, verbose_name='October-17'),
        ),
        migrations.AlterField(
            model_name='historicalcomputeprofile',
            name='compute_sep',
            field=models.CharField(max_length=10, verbose_name='September-17'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='project_class',
            field=models.CharField(max_length=30, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='project_contact_primary',
            field=models.CharField(max_length=30, verbose_name='Primary Contact'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='project_contact_secondary',
            field=models.CharField(blank=True, default='None', max_length=30, null=True, verbose_name='Secondary Contact'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='project_version',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9)], max_length=5, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_apr',
            field=models.CharField(max_length=10, verbose_name='April-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_aug',
            field=models.CharField(max_length=10, verbose_name='August-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_dec',
            field=models.CharField(max_length=10, verbose_name='December-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_feb',
            field=models.CharField(max_length=10, verbose_name='February-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_jan',
            field=models.CharField(max_length=10, verbose_name='January-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_jul',
            field=models.CharField(max_length=10, verbose_name='July-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_jun',
            field=models.CharField(max_length=10, verbose_name='June-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_mar',
            field=models.CharField(max_length=10, verbose_name='March-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_may',
            field=models.CharField(max_length=10, verbose_name='May-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_nov',
            field=models.CharField(max_length=10, verbose_name='November-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_oct',
            field=models.CharField(max_length=10, verbose_name='October-17'),
        ),
        migrations.AlterField(
            model_name='historicalstorageprofile',
            name='storage_sep',
            field=models.CharField(max_length=10, verbose_name='September-17'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_class',
            field=models.CharField(max_length=30, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_contact_primary',
            field=models.CharField(max_length=30, verbose_name='Primary Contact'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_contact_secondary',
            field=models.CharField(blank=True, default='None', max_length=30, null=True, verbose_name='Secondary Contact'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_version',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9)], max_length=5, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='slotsorhosts',
            name='slots_or_hosts',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_apr',
            field=models.CharField(max_length=10, verbose_name='April-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_aug',
            field=models.CharField(max_length=10, verbose_name='August-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_dec',
            field=models.CharField(max_length=10, verbose_name='December-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_feb',
            field=models.CharField(max_length=10, verbose_name='February-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_jan',
            field=models.CharField(max_length=10, verbose_name='January-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_jul',
            field=models.CharField(max_length=10, verbose_name='July-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_jun',
            field=models.CharField(max_length=10, verbose_name='June-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_mar',
            field=models.CharField(max_length=10, verbose_name='March-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_may',
            field=models.CharField(max_length=10, verbose_name='May-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_nov',
            field=models.CharField(max_length=10, verbose_name='November-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_oct',
            field=models.CharField(max_length=10, verbose_name='October-17'),
        ),
        migrations.AlterField(
            model_name='storageprofile',
            name='storage_sep',
            field=models.CharField(max_length=10, verbose_name='September-17'),
        ),
        migrations.AlterField(
            model_name='storagesize',
            name='storage_size',
            field=models.CharField(max_length=15),
        ),
    ]
