# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0037_auto_20170814_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computeprofile',
            name='compute_apr',
            field=models.CharField(blank=True, default=0, max_length=10, null=True, verbose_name='April-17'),
        ),
        migrations.AlterField(
            model_name='historicalcomputeprofile',
            name='compute_apr',
            field=models.CharField(blank=True, default=0, max_length=10, null=True, verbose_name='April-17'),
        ),
    ]
